version: '{branch}.{build}'
image: Visual Studio 2019
configuration: Release
platform: x64
clone_depth: 5
cache:
- C:\tools\vcpkg\installed
environment:
  CODE_SIGNING_CLOUD:
    secure: A3e3o/F1R4NmHP5DD/4VvG63efa6NaM4pq3WTH8BSnyUfSZQYB4ph4rRhPptsl1D
  VCPKG_PLATFORM_TOOLSET: v142
  PATH: 'C:\Python37-x64;C:\Python37-x64\Scripts;%PATH%'
  PYTHONUTF8: 1
install:
- ps: |
      cd c:\tools\vcpkg
      $env:GIT_REDIRECT_STDERR = '2>&1' # git is writing non-errors to STDERR when doing git pull. Send to STDOUT instead.
      git pull origin master > $null
      .\bootstrap-vcpkg.bat > $null
      vcpkg integrate install
      vcpkg install --triplet x64-windows-static berkeleydb
      vcpkg install --triplet x64-windows-static boost-filesystem
      vcpkg install --triplet x64-windows-static boost-multi-index
      vcpkg install --triplet x64-windows-static boost-process
      vcpkg install --triplet x64-windows-static boost-signals2
      vcpkg install --triplet x64-windows-static boost-test
      vcpkg install --triplet x64-windows-static boost-thread
      vcpkg install --triplet x64-windows-static sqlite3
      vcpkg install --triplet x64-windows-static libevent[thread]
      vcpkg install --triplet x64-windows-static double-conversion
      vcpkg install --triplet x64-windows-static zeromq
      vcpkg install --triplet x64-windows-static icu
      vcpkg install --triplet x64-windows-static pcre2
      vcpkg install --triplet x64-windows-static libjpeg-turbo
      vcpkg install --triplet x64-windows-static libpq[openssl,zlib]
      vcpkg install --triplet x64-windows-static qt5-base
      vcpkg install --triplet x64-windows-static libqrencode
      vcpkg install --triplet x64-windows-static miniupnpc
      cd "$env:APPVEYOR_BUILD_FOLDER"
before_build:
- cmd: python build_msvc\msvc-autogen.py
build_script:
- cmd: msbuild /p:TrackFileAccess=false build_msvc\bitcoin.sln /v:q /nologo
after_build:
- cmd: '"C:\Program Files (x86)\NSIS\makensis.exe" build_msvc\setup.nsi'
- cmd: build_msvc\sign.bat
artifacts:
- path: bitcoin-%APPVEYOR_BUILD_VERSION%-setup.exe
deploy:
  provider: GitHub
  auth_token:
    secure: uiOiWPYkpsG1/nDKwbUTW5WjG1o2VatrLkho8PK49Q9hteRSk7vO5cpnRscCMreR
  artifact: bitcoin-%APPVEYOR_BUILD_VERSION%-setup.exe
  on:
    APPVEYOR_REPO_TAG: true
